### ISSUE TITLE
Update for AllureSelenide results in error

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [allure-framework/allure-java#366]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
java.lang.NoSuchMethodError: io.qameta.allure.util.AnnotationUtils.getLinks(Ljava/lang/reflect/AnnotatedElement;)Ljava/util/List;

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Allure Selenide works with Selenide 5.2.2 and AllureSelenide 2.10.0
and doesn't work with Selenide 5.2.3 and AllureSelenide 2.12.1

#### What is the expected behavior?
AllureSelenide works as it had before

#### Please tell us about your environment:
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <webdrivermanager.version>3.6.0</webdrivermanager.version>
        <allure-testng.version>2.11.0</allure-testng.version>
        <jackson.version>2.9.8</jackson.version>
        <testng.version>6.14.3</testng.version>
        <aspectj.version>1.9.2</aspectj.version>
        <selenide.version>5.2.3</selenide.version>
        <slf4j-nop.version>1.8.0-beta4</slf4j-nop.version>
        <maven-surefire-plugin.version>3.0.0-M3</maven-surefire-plugin.version>
        <jsoup.version>1.11.3</jsoup.version>
        <org.yaml.version>1.24</org.yaml.version>
        <org.json.version>20180813</org.json.version>
        <maven-compiler.version>3.8.0</maven-compiler.version>
        <log4j.version>1.2.17</log4j.version>

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by AlexanderPoleschuk** [comment]
Update to <allure-testng.version>2.12.1</allure-testng.version> fixed the issue.
