### ISSUE TITLE
Cucumber 4.2.1 throws error

### ISSUE THREAD

**Issue by jsa34** [allure-framework/allure-java#307]
#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Cucumber4JVM supports up to 4.2.0 - fails with 4.2.1 due to CucumberFeature now requiring a list of PickleEvent s to be passed.

```
> Task :allure-cucumber4-jvm:compileTestJava FAILED
/home/jenkins/workspace/allure-java_PR-303-SZPSDZZETWBSMJCQM4QHGCZCXCLWQSB7QV6Q2BUSSPZDXE62XCAQ/allure-cucumber4-jvm/src/test/java/io/qameta/allure/cucumber4jvm/AllureCucumber4JvmTest.java:613: error: constructor CucumberFeature in class CucumberFeature cannot be applied to given types;
                CucumberFeature feature = new CucumberFeature(gherkinDocument, featureResource, gherkin);
                                          ^
  required: GherkinDocument,String,String,List<PickleEvent>
  found: GherkinDocument,String,String
  reason: actual and formal argument lists differ in length
1 error

> Task :allure-descriptions-javadoc:spotbugsMain
> Task :allure-cucumber4-jvm:spotbugsMain

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':allure-cucumber4-jvm:compileTestJava'.
> Compilation failed; see the compiler error output for details.

```
See: [https://ci.qameta.io/job/allure-java/job/PR-303/2/console](https://ci.qameta.io/job/allure-java/job/PR-303/2/console) for an example build with 4.2.1 on CucumberJVM4

**Comment by jsa34** [comment]
Now fixed and merged into master
