### ISSUE TITLE
allure-spock is not working with spock-core 2.0-M3-groovy-2.5 version

### ISSUE THREAD

**Issue by hemavar** [allure-framework/allure-java#466]
#### I'm submitting a ... 
  - [ ] feature request

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

I don't know if allure-spock supports 2.0-M3-groovy-2.5 version currently, as there is not much documentation about the same. 
I was using allure-spock version-2.13 with spock-core version 1.3-groovy-2.5 and it works fine.  

#### What is the current behavior?

[main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: test case with uuid 6c6588dd-52f5-4999-8bb3-c87622d94852 not found
[main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: test case with uuid 6c6588dd-52f5-4999-8bb3-c87622d94852 not found
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.193 s <<< FAILURE! - in ExampleSpec
[ERROR] ExampleSpec.Get message one  Time elapsed: 0.164 s  <<< ERROR!
java.lang.NoSuchMethodError: org.spockframework.runtime.model.FeatureInfo.getDescription()Lorg/junit/runner/Description;
#### What is the motivation / use case for changing the behavior?
I was trying to upgrade spock-core version to 2.0 for making use of some new features. However, allure-spock doesn't seem to work.  When is the next allure-spock release expected?

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | spock@2.0-M1-groovy-2.5 |
| Allure integration | allure-spock@2.13.0 |
| Generate report using | allure-maven@2.10 |

**Comment by feanor777** [comment]
The issue is definitely not resolved, and as I see, some other request is opened
https://github.com/allure-framework/allure-java/issues/510
